const $ = selector => document.querySelector(selector);
const ORDER_ACTION_URL = "https://us-central1-menassafigs.cloudfunctions.net/acceptOnlineOrder";
const db = window.ORDERING_FIREBASE?.database;
let orders = [], activeTab = "new", page = 1, pageSize = 10;
const money = value => `${Number(value || 0).toFixed(3)} د.ك`;
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[char]));
const dateText = value => value ? new Date(Number(value) || value).toLocaleString("ar-KW", { dateStyle:"medium", timeStyle:"short" }) : "—";
const deliveryText = order => order.mode === "pickup" ? "استلام من الفرع" : `توصيل${order.areaName ? ` — ${order.areaName}` : ""}`;
const dueText = order => {
  const seconds = Math.max(0, Math.floor((Date.now() - Number(order.createdAt || Date.now())) / 1000));
  const hours = String(Math.floor(seconds / 3600)).padStart(2, "0"), minutes = String(Math.floor((seconds % 3600) / 60)).padStart(2, "0"), secs = String(seconds % 60).padStart(2, "0");
  return `${hours}:${minutes}:${secs}`;
};
function filteredOrders() { return orders.filter(order => activeTab === "new" ? order.status !== "accepted" : order.status === "accepted").sort((a,b) => Number(b.createdAt || 0) - Number(a.createdAt || 0)); }
function render() {
  const listed = filteredOrders(), pages = Math.max(1, Math.ceil(listed.length / pageSize)); page = Math.min(page, pages);
  $("#newCount").textContent = orders.filter(order => order.status !== "accepted").length; $("#acceptedCount").textContent = orders.filter(order => order.status === "accepted").length;
  $("#tableTitle").textContent = activeTab === "new" ? "الطلبات الجديدة" : "الطلبات المقبولة";
  $("#tableHint").textContent = activeTab === "new" ? "طلبات تحتاج إلى قبول" : "طلبات تم قبولها وجاهزة للطباعة";
  $("#ordersHead").innerHTML = activeTab === "new" ? "<tr><th>عرض</th><th>رقم الفاتورة</th><th>الاسم</th><th>رقم الهاتف</th><th>السعر الإجمالي</th><th>طريقة التوصيل</th><th>تاريخ الإنشاء</th><th>موعد التوصيل</th><th>انقضى</th></tr>" : "<tr><th>عرض</th><th>رقم الفاتورة</th><th>الاسم</th><th>رقم الهاتف</th><th>السعر الإجمالي</th><th>طريقة التوصيل</th><th>تاريخ الإنشاء</th></tr>";
  const pageOrders = listed.slice((page - 1) * pageSize, page * pageSize);
  $("#ordersBody").innerHTML = pageOrders.length ? pageOrders.map(order => activeTab === "new" ? `<tr><td><button class="view-button" data-view="${escapeHtml(order.orderId)}">عرض</button></td><td class="invoice-number">${escapeHtml(order.orderId)}</td><td><strong>${escapeHtml(order.customerName || "—")}</strong></td><td dir="ltr">${escapeHtml(order.phone || "—")}</td><td>${money(order.total)}</td><td>${escapeHtml(deliveryText(order))}</td><td>${dateText(order.createdAt)}</td><td>${order.scheduledAt ? dateText(order.scheduledAt) : order.deliveryTiming === "asap" ? "أقرب وقت" : "عند الجاهزية"}</td><td><span class="elapsed" data-elapsed="${escapeHtml(order.orderId)}">${dueText(order)}</span></td></tr>` : `<tr><td><button class="view-button" data-view="${escapeHtml(order.orderId)}">عرض</button></td><td class="invoice-number">${escapeHtml(order.orderId)}</td><td><strong>${escapeHtml(order.customerName || "—")}</strong></td><td dir="ltr">${escapeHtml(order.phone || "—")}</td><td>${money(order.total)}</td><td>${escapeHtml(deliveryText(order))}</td><td>${dateText(order.createdAt)}</td></tr>`).join("") : `<tr class="empty-row"><td colspan="9">${activeTab === "new" ? "لا توجد طلبات جديدة حالياً" : "لا توجد طلبات مقبولة حالياً"}</td></tr>`;
  $("#pageInfo").textContent = `${page} / ${pages}`; $("#previousPage").disabled = page <= 1; $("#nextPage").disabled = page >= pages;
}
function refreshTimers() { document.querySelectorAll("[data-elapsed]").forEach(node => { const order = orders.find(item => item.orderId === node.dataset.elapsed); if (order) node.textContent = dueText(order); }); }
function invoiceHtml(order) { return `<section class="invoice"><header class="invoice-head"><div class="invoice-brand"><img src="logo.png"><div><h1>مخبز التين والزيتون</h1><p>Figs &amp; Olives Bakery</p></div></div><div class="invoice-no"><small>فاتورة مبيعات / SALES INVOICE</small><b>#${escapeHtml(order.orderId)}</b><small>${dateText(order.createdAt)}</small></div></header><section class="company"><b>معلومات الشركة / COMPANY</b><br>شركة صحي ولذيذ للتجهيزات الغذائية<br>Healthy &amp; Delicious Foodstuff Co.<br>66906605 · 22085888</section><section class="parties"><div><span>العميل / CUSTOMER</span><b>${escapeHtml(order.customerName || "—")}</b><p dir="ltr">${escapeHtml(order.phone || "—")}</p></div><div><span>${order.mode === "pickup" ? "الاستلام / PICKUP" : "عنوان التوصيل / DELIVERY"}</span><b>${escapeHtml(order.mode === "pickup" ? order.branchId || "الفرع" : `${order.areaName || ""} — ${order.address || ""}`)}</b><p>${order.scheduledAt ? dateText(order.scheduledAt) : order.deliveryTiming === "asap" ? "أقرب وقت متاح" : "إبلاغ العميل عند الجاهزية"}</p></div></section><table><thead><tr><th>#</th><th>الصنف / ITEM</th><th>ملاحظات / NOTES</th><th>الكمية / QTY</th><th>سعر الوحدة / UNIT PRICE</th><th>الإجمالي / TOTAL</th></tr></thead><tbody>${(order.items || []).map((item,index) => `<tr><td>${index+1}</td><td><b>${escapeHtml(item.name || item.nameAr || item.id)}</b><small dir="ltr">${escapeHtml(item.nameEn || item.name || item.id)}</small></td><td>${escapeHtml(item.note || "—")}</td><td>${item.quantity}</td><td>${money(item.unitPrice)}</td><td>${money(item.total || item.unitPrice * item.quantity)}</td></tr>`).join("")}</tbody></table><div class="grand"><span>الإجمالي / TOTAL</span><b>${money(order.total)}</b></div></section>`; }
function showOrder(order) { $("#orderDetails").innerHTML = `<div class="order-header"><div><small>طلب أونلاين</small><h2>#${escapeHtml(order.orderId)}</h2><small>${dateText(order.createdAt)}</small></div><span class="order-status">${order.status === "accepted" ? "تم القبول" : "بانتظار القبول"}</span></div><div class="detail-grid"><div><span>العميل</span><b>${escapeHtml(order.customerName || "—")}</b></div><div><span>رقم الهاتف</span><b dir="ltr">${escapeHtml(order.phone || "—")}</b></div><div><span>التوصيل</span><b>${escapeHtml(deliveryText(order))}</b></div><div><span>العنوان / الفرع</span><b>${escapeHtml(order.mode === "pickup" ? order.branchId || "—" : `${order.areaName || ""} — ${order.address || ""}`)}</b></div><div><span>موعد التوصيل</span><b>${order.scheduledAt ? dateText(order.scheduledAt) : order.deliveryTiming === "asap" ? "أقرب وقت" : "عند الجاهزية"}</b></div><div><span>طريقة الدفع</span><b>${String(order.paymentMethod || "KNET").toUpperCase()}</b></div></div>${invoiceHtml(order).replace('class="invoice"','class="items-invoice"').replace('<section class="company"','<section class="company"').replace('<header class="invoice-head"','<header class="invoice-head"')}<div class="dialog-actions">${order.status === "accepted" ? `<button class="print-button" data-print="${escapeHtml(order.orderId)}">طباعة الطلب</button>` : `<button class="accept-button" data-accept="${escapeHtml(order.orderId)}">قبول الطلب</button>`}</div>`; $("#orderDialog").showModal(); }
async function acceptOrder(orderId) { const button = document.querySelector(`[data-accept="${CSS.escape(orderId)}"]`); if (button) { button.disabled = true; button.textContent = "جارٍ القبول…"; } try { const response = await fetch(ORDER_ACTION_URL,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({orderId})}); const data = await response.json().catch(()=>({})); if (!response.ok || !data.ok) throw new Error(data.error || "تعذر قبول الطلب"); $("#orderDialog").close(); } catch(error) { alert(error.message || "تعذر قبول الطلب"); if (button) { button.disabled=false; button.textContent="قبول الطلب"; } } }
function printOrder(order) { document.querySelector(".print-sheet")?.remove(); const sheet = document.createElement("div"); sheet.className="print-sheet"; sheet.innerHTML=invoiceHtml(order); document.body.append(sheet); window.print(); sheet.remove(); }
function setSound() { const audio=$("#newOrderSound"), hasNew=orders.some(order=>order.status!=="accepted"); audio.volume=1; if (hasNew) audio.play().catch(()=>undefined); else { audio.pause(); audio.currentTime=0; } }
document.addEventListener("pointerdown", setSound, { passive: true });
document.querySelectorAll("[data-tab]").forEach(button=>button.onclick=()=>{activeTab=button.dataset.tab; page=1; document.querySelectorAll("[data-tab]").forEach(tab=>tab.classList.toggle("active",tab===button)); render();});
$("#pageSize").onchange=event=>{pageSize=Number(event.target.value);page=1;render();}; $("#previousPage").onclick=()=>{page--;render();}; $("#nextPage").onclick=()=>{page++;render();}; $("#closeDialog").onclick=()=>$("#orderDialog").close(); $("#orderDialog").onclick=event=>{if(event.target===$("#orderDialog")) $("#orderDialog").close();};
document.addEventListener("click",event=>{const view=event.target.closest("[data-view]"),accept=event.target.closest("[data-accept]"),print=event.target.closest("[data-print]");if(view){const order=orders.find(item=>item.orderId===view.dataset.view);if(order)showOrder(order);}if(accept)acceptOrder(accept.dataset.accept);if(print){const order=orders.find(item=>item.orderId===print.dataset.print);if(order)printOrder(order);}});
if (!db) { $("#ordersBody").innerHTML='<tr class="empty-row"><td colspan="9">تعذر الاتصال بقاعدة البيانات.</td></tr>'; } else window.ORDERING_FIREBASE.auth.signInAnonymously().catch(()=>undefined).finally(()=>db.ref("orderingPlatform/onlineOrders").on("value",snapshot=>{orders=Object.values(snapshot.val()||{});render();setSound();},()=>{$("#ordersBody").innerHTML='<tr class="empty-row"><td colspan="9">تعذر قراءة الطلبات. تأكد من نشر قواعد Firebase الجديدة.</td></tr>';}));
setInterval(refreshTimers,1000); render();
